### ISSUE TITLE
Tracking issue for 0.3.0 release

### ISSUE THREAD

**Issue by j-ti** [rl-institut/smooth#231]
Prepare
* [x] Go through branches together: keep/ create PR/ delete

Do
* [x] Testing (Check all components also for the "Adapt new oemof structure #113 "):
  * [x] all tests written - **Stefan**, Ciara, Julian (25.2)
  * [x] review tests #236 - Julian (25.3.)
  * [x] run tests with new oemof structure #113 
* [x] Issues:
  * [x] #234  - @b-r-u ?
  * [x] Activate Travis again - @b-r-u ?
  * [x] #233 - delete interactive plotting function - Ciara (25.2.)
  * [x] #173 store save important parameters locally (GOGS) and delete function - Ciara (25.2)
  * [x] also delete rtd for 'interactive plotting function' and 'save important parameters '  - Ciara (25.2)
* [x] PRs:
  * [x] #235 - Julian (11.3.)
  * [x] #181 - Julian (11.3.)
  * [x] steam methane reformer - Ciara prepares PR #243 - julian/laura (25.2.)
  * [x] unify create_oemof_model behaviour -> rename: add_to_oemof_model - julian (25.3.) #251 
  * [x] julian makes PR: delete DC AC and AC DC generate generic electric converter - julian (11.3.) #248 
  * [x] include oemof.thermal - julian (11.3.) part of #113 
  * [x] merge #113 

Finalize
* [x] Release `0.3.0` by changing setup.py, doc/conf.py and adding a tag to commit
* [x] Check all requirements
* [x] Fix flake8 warnings
* [x] Update Changelog (also how to change from 0.2.0 to 0.3.0)
* [x] merge master
* [x] :robot: :tada:
