### ISSUE TITLE
Examples for all components wanted

### ISSUE THREAD

**Issue by j-brendel** [rl-institut/smooth#254]
To facilitate a basic understanding of each component, there is a need to have test for all of them. This list summarizes what already exists and what not

* [ ] we want to explain all components with examples
    * [x] AC:zap:DC Converter (JB) #245
    * [ ] Air Source Heat Pump
    * [x]  Battery (JB) #245
    * [x] Compressor H2
    * [x] DC/AC Inverter (JB) #245
    * [x] Electric Heater (JB) #245
    * [x] Electrolyzer
    * [ ] Electrolyzer Waste Heat
    * [x] Energy Demand From CSV
    * [x] Energy Source From CSV
    * [x] Fuel Cell CHP
    * [ ] Gas Engine CHP Biogas
    * [x] Gate
    * [ ] H2 CHP
    * [ ] H2 Refuel Cooling System
    * [ ] PEM Electrolyzer
    * [x]  Sink
    * [x] Storage H2
    * [ ] Stratified Thermal Storage
    * [x]  Supply
    * [x] Trailer Gate
    * [ ] Trailer Gate Cascade
    * [x] Trailer H2 Delivery
    * [ ] Trailer H2 Delivery Cascade
    * [x] Trailer H2 Delivery Single
    * [x] External Component
    * [x] External Component H2 Dispenser
