### ISSUE TITLE
Tracking issue for 0.2.0 release

### ISSUE THREAD

**Issue by b-r-u** [rl-institut/smooth#55]
* [x] Create Commits, PRs for local changes
* [x] Merge existing PRs
* [x] Go through branches together: keep/ create PR/ delete
* [x] Change components in model definition from array to dict #56
* [x] Add feature to load models from JSON  #57
* [x] Add Sphinx docs, connect with readthedocs #63
* [x] Merge improved plotting function #77
* [x] Check all requirements
* [x] Change reference to oemof not on PR but a stable commit #28
* [x] Fix flake8 warnings and include flake8 in travis.yml #88
* [x] Update Changelog https://github.com/rl-institut/smooth/pull/89
* [x] Release `0.2.0` by changing setup.py, doc/conf.py and adding a tag to this commit https://github.com/rl-institut/smooth/pull/89
* [x] clean up issues and (local/ remote) branches
* [x] :robot: :tada:

**Comment by b-r-u** [comment]
:tada:
